language: java

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/dists/
before_cache:
  - find $HOME/.gradle -name "*.lock" -exec rm {} \;
  - rm -rf $HOME/.gradle/caches/[1-9]*

matrix:
  include:
    - jdk: oraclejdk8
    - jdk: openjdk7
      env: COVERAGE="true" RELEASE="true"

after_success:
- if [ "$COVERAGE" = "true" ]; then ./gradlew jacocoTestReport coveralls; fi
- if [ "$RELEASE" = "true" ]; then ./gradlew bintrayUpload; fi

env:
  global:
  - bintrayUser=kruton
  - secure: "GsKArxsSYwcp2jWfAR/pLbuWd2bureCX144TLFkfon27s6Sf2a/7uxL7iX9YUbMjQ1glRJkovdxA80euykPgU0wAUts/Pxo/GtB7F7n66sQgCa5nQ1eQIY4MckvRKRuJIk3VK2t6Pq8cSQijqXX/PRbsLtinkIEFewQIdNoDOAbD8wZTEBAHtJs95fp2S214ZvR4QG7EPRvgGx/XpRkO1zsjS3b/ec5+fjJZBHt67I6y7SWQSIf99AAiiGnY4Z9n3oVzsIgjDa7S2SVZ2iDSQLWIufTvTfm8gvUTetIQ0cGb9nFoC5K45jQKV4Ca6WHKmRbt2AwDu0sYZ69YdGI9E9yjCB/FxAJg8K+Sowq4Tg+CP6czk5N6o0Qic0zhSDjBDsX7o4jo+A52wYCvatMmD7SCFCMnip1zWMJ7lCUxz69UqTgArOFOLT21RLRBPM4UDbo+cN69uSwWvvNX/qMhL7ZM0kQtY0onXtIAoKC7R1BrdzKl+HzkTGrqAUBLgrlQWQKQq66EQfI+foQykUYrNdfyignj4Pxg5QtNchs6BIsbhZGkSDS7z9MV45pKEhnawsMm48/fZF9EH29Y612/l2mIU48xlSCV47SqUxowzZsmrp+Xbj6biTr8hBOG+4UU15lZXKuDkC+bGhCcOBqOzcD1gXe6QvbddPlnzanwQkU="
